services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tech_solutions_app
    restart: always
    ports:
      - "3007:3000"
    environment:
      - DATABASE_URL
      - NEXTAUTH_SECRET
      - NEXTAUTH_URL
      - RESEND_API_KEY
    volumes:
      - uploads_data:/app/public/uploads
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    container_name: tech_hub_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-tech_hub}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  uploads_data:
